[package]
name = "arena_net"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]

[dependencies]
actix = "0.7.4"
actix-web = "0.7.7"
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.27"

arena_core = { path = "../arena_core" }
nanoid = "0.2.0"
