[package]
name = "arena_net"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]

[dependencies]
actix = "0.7.5"
actix-web = "0.7.12"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.32"
ws = "0.7.8"

arena_core = { path = "../arena_core" }
nanoid = "0.2.0"
