[package]
name = "arena_bin"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]

[dependencies]
arena_core = { path = "../arena_core" }
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.27"
